"""empty message

Revision ID: a8bd2c00a3e2
Revises: ba6ac9cb37f2
Create Date: 2023-10-08 04:08:36.760825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bd2c00a3e2'
down_revision = 'ba6ac9cb37f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biter',
    sa.Column('creature_id', sa.Integer(), nullable=False),
    sa.Column('bug_bite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bug_bite_id'], ['bug_bites.id'], name=op.f('fk_biter_bug_bite_id_bug_bites')),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], name=op.f('fk_biter_creature_id_creatures')),
    sa.PrimaryKeyConstraint('creature_id', 'bug_bite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biter')
    # ### end Alembic commands ###
