"""import models attempt 1

Revision ID: ba6ac9cb37f2
Revises: a58b7657eb9f
Create Date: 2023-10-06 12:59:49.719827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6ac9cb37f2'
down_revision = 'a58b7657eb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bite_treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_plan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('bug_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'bug_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bug_bites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bite_description', sa.String(), nullable=False),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('severity_of_bite', sa.String(), nullable=True),
    sa.Column('treatment_plan_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('LENGTH(bite_description) >= 10'),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['bite_treatments.id'], name=op.f('fk_bug_bites_treatment_plan_id_bite_treatments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug_bites')
    op.drop_table('users')
    op.drop_table('creatures')
    op.drop_table('bite_treatments')
    # ### end Alembic commands ###
