"""Add user_id column and relationships to BugBite model

Revision ID: cff3fbb6ed6a
Revises: de6822bf4e8d
Create Date: 2023-10-08 21:31:37.914631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff3fbb6ed6a'
down_revision = 'de6822bf4e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug_bites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bug_bites_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug_bites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bug_bites_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
